import { deepTree } from '@oceancode/ocean-wui'

export function loadSystemMenu(){
  return deepTree([
    {
      id:"38",
      parentId:"",
      label:"系统管理",
      key:"38",
      layoutVisible:{
        menu:true
      },
    },
    {
      id:"39",
      parentId:"",
      label:"数据管理",
      key:"39",
    },
    {
      id:"40",
      parentId:"38",
      label:"权限管理",
      key:"40",
      layoutVisible:{
        menu:true
      },
    },
    {
      id:"41",
      parentId:"40",
      label:"用户列表",
      key:"userList",
      router:{
        name:'userList'
      },
    },
    {
      id:"45",
      parentId:"40",
      label:"菜单列表",
      key:"menuList",
      router:{
        name:'menuList'
      },
    },
    {
      id:"46",
      parentId:"40",
      label:"角色列表",
      key:"roleList",
      router:{
        name:'roleList'
      },
    },
    {
      id:"47",
      parentId:"38",
      label:"参数配置",
      key:"47",
      layoutVisible:{
        menu:true
      },
    },
    {
      id:"48",
      parentId:"47",
      label:"参数列表",
      key:"48",
    },
  ])
}