/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAccount: typeof import('./src/components/custom/account/AddAccount.vue')['default']
    AddMenu: typeof import('./src/components/custom/menu/AddMenu.vue')['default']
    AppContext: typeof import('./src/components/common/AppContext.vue')['default']
    AppRouter: typeof import('./src/components/common/AppRouter.vue')['default']
    AppRouterContext: typeof import('./src/components/common/AppRouterContext.vue')['default']
    MessageContent: typeof import('./src/components/common/MessageContent.vue')['default']
    ModelLinkName: typeof import('./src/components/custom/model/model-link-name.vue')['default']
    ModelSelect: typeof import('./src/components/custom/model/ModelSelect.vue')['default']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    OAddButton: typeof import('@oceancode/ocean-wui')['OAddButton']
    OAdminLayout: typeof import('@oceancode/ocean-wui')['OAdminLayout']
    OAvatar: typeof import('@oceancode/ocean-wui')['OAvatar']
    OContext: typeof import('@oceancode/ocean-wui')['OContext']
    ODataList: typeof import('@oceancode/ocean-wui')['ODataList']
    ODataTable: typeof import('@oceancode/ocean-wui')['ODataTable']
    ODrawer: typeof import('@oceancode/ocean-wui')['ODrawer']
    ODropdown: typeof import('@oceancode/ocean-wui')['ODropdown']
    OForm: typeof import('@oceancode/ocean-wui')['OForm']
    OImage: typeof import('@oceancode/ocean-wui')['OImage']
    OInputGroup: typeof import('@oceancode/ocean-wui')['OInputGroup']
    OLayoutMenu: typeof import('@oceancode/ocean-wui')['OLayoutMenu']
    OLayoutSquareNavMenu: typeof import('@oceancode/ocean-wui')['OLayoutSquareNavMenu']
    OMenu: typeof import('@oceancode/ocean-wui')['OMenu']
    ORootContext: typeof import('@oceancode/ocean-wui')['ORootContext']
    OSegmentTabs: typeof import('@oceancode/ocean-wui')['OSegmentTabs']
    OSelect: typeof import('@oceancode/ocean-wui')['OSelect']
    OSpace: typeof import('@oceancode/ocean-wui')['OSpace']
    OSubmitButton: typeof import('@oceancode/ocean-wui')['OSubmitButton']
    OSwitch: typeof import('@oceancode/ocean-wui')['OSwitch']
    OText: typeof import('@oceancode/ocean-wui')['OText']
    OTreeSelect: typeof import('@oceancode/ocean-wui')['OTreeSelect']
    PageLinkName: typeof import('./src/components/custom/page/page-link-name.vue')['default']
    PageParam: typeof import('./src/components/custom/page/PageParam.vue')['default']
    PageSelect: typeof import('./src/components/custom/page/PageSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskStatus: typeof import('./src/components/custom/status/TaskStatus.vue')['default']
    UpdateAccount: typeof import('./src/components/custom/account/UpdateAccount.vue')['default']
    UpdateMenu: typeof import('./src/components/custom/menu/UpdateMenu.vue')['default']
    VisibleConfig: typeof import('./src/components/custom/menu/visible-config.vue')['default']
  }
}
