/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContext: typeof import('./src/components/common/AppContext.vue')['default']
    AppRouter: typeof import('./src/components/common/AppRouter.vue')['default']
    AppRouterContext: typeof import('./src/components/common/AppRouterContext.vue')['default']
    MessageContent: typeof import('./src/components/common/MessageContent.vue')['default']
    MyComponent: typeof import('./src/components/custom/MyComponent.vue')['default']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    OAddButton: typeof import('@oceancode/ocean-wui')['OAddButton']
    OAppGiteeIcon: typeof import('@oceancode/ocean-wui')['OAppGiteeIcon']
    OBox: typeof import('@oceancode/ocean-wui')['OBox']
    OButton: typeof import('@oceancode/ocean-wui')['OButton']
    OCategoryGroup: typeof import('@oceancode/ocean-wui')['OCategoryGroup']
    OContainer: typeof import('@oceancode/ocean-wui')['OContainer']
    OContext: typeof import('@oceancode/ocean-wui')['OContext']
    OCustomSiderLayout: typeof import('@oceancode/ocean-wui')['OCustomSiderLayout']
    ODataList: typeof import('@oceancode/ocean-wui')['ODataList']
    ODataTable: typeof import('@oceancode/ocean-wui')['ODataTable']
    ODeleteIcon: typeof import('@oceancode/ocean-wui')['ODeleteIcon']
    ODialog: typeof import('@oceancode/ocean-wui')['ODialog']
    ODivider: typeof import('@oceancode/ocean-wui')['ODivider']
    ODrawer: typeof import('@oceancode/ocean-wui')['ODrawer']
    OForm: typeof import('@oceancode/ocean-wui')['OForm']
    OGroupTree: typeof import('@oceancode/ocean-wui')['OGroupTree']
    OIframeView: typeof import('@oceancode/ocean-wui')['OIframeView']
    OImage: typeof import('@oceancode/ocean-wui')['OImage']
    OInput: typeof import('@oceancode/ocean-wui')['OInput']
    OInputNumber: typeof import('@oceancode/ocean-wui')['OInputNumber']
    OLoginButton: typeof import('@oceancode/ocean-wui')['OLoginButton']
    ONoticeIcon: typeof import('@oceancode/ocean-wui')['ONoticeIcon']
    OPagination: typeof import('@oceancode/ocean-wui')['OPagination']
    OQuery: typeof import('@oceancode/ocean-wui')['OQuery']
    ORefreshButton: typeof import('@oceancode/ocean-wui')['ORefreshButton']
    ORootContext: typeof import('@oceancode/ocean-wui')['ORootContext']
    ORunIcon: typeof import('@oceancode/ocean-wui')['ORunIcon']
    OSearchInput: typeof import('@oceancode/ocean-wui')['OSearchInput']
    OSelect: typeof import('@oceancode/ocean-wui')['OSelect']
    OTag: typeof import('@oceancode/ocean-wui')['OTag']
    OText: typeof import('@oceancode/ocean-wui')['OText']
    OUserDropdown: typeof import('@oceancode/ocean-wui')['OUserDropdown']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
